baseURL = "https://girigiribauer.com/"
languageCode = "ja-jp"
title = "ばうあーろぐ"
enableRobotsTXT = true
enableEmoji = true

# Preserve legacy URL structure
[permalinks]
tech = "/tech/:contentbasename/"
biz = "/biz/:contentbasename/"
misc = "/misc/:year:month:day/"

[taxonomies]
tag = "tags"

[markup.goldmark.renderer]
unsafe= true

[params]
    author = "girigiribauer"
    description = "IT / Web に関するメモ、あるいは Twentyfour あるいは人生の diff"
    images = ["/img/ogimage.png"]
    twitter = "@girigiribauer"


